version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Backend API on port 8000
    volumes:
      - ./backend/app:/code/app  # Mount local code for hot-reloading
    environment:
      - DATABASE_URL=postgresql://dota_user:dota_password@db:5432/dota_db
      - DEBUG=True
      - LOG_LEVEL=INFO
    depends_on:
      - db
    command: uvicorn app.main_new:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend/dota-2-project
    ports:
      - "3000:3000"  # Nuxt dev server on port 3000
    volumes:
      - ./frontend/dota-2-project:/app  # Mount entire Nuxt project
      - /app/node_modules  # Prevent overwriting node_modules
      - /app/.nuxt  # Prevent overwriting .nuxt build directory
    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    command: bun run dev --host 0.0.0.0

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dota_user
      - POSTGRES_PASSWORD=dota_password
      - POSTGRES_DB=dota_db
    ports:
      - "5432:5432"  # PostgreSQL on port 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dota_user -d dota_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
